name: CI

on:
  pull_request:
    branches:
      - main  # Replace with your actual default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add your build, test, or lint steps here
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Provision KinD Cluster
        run: |
          chmod +x ./scripts/provision_kind_cluster.sh
          ./scripts/provision_kind_cluster.sh

      - name: Run Tests
        run: |
          # Add commands to run your tests here
          echo "Running tests..." 

      - name: Cleanup KinD Cluster
        run: |
          kind delete cluster --name your-cluster-name