name: CI

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add your build, test, or lint steps here
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Provision KinD Cluster
        run: |
          chmod +x ./scripts/provision_kind_cluster.sh
          ./scripts/provision_kind_cluster.sh

      - name: Install hey
        run: |
          curl -LO https://github.com/hatoo/oha/releases/download/v1.8.0/oha-linux-amd64
          file oha-linux-amd64 | grep 'ELF 64-bit' || (echo "Download failed or not a Linux binary" && cat oha-linux-amd64 && exit 1)
          chmod +x oha-linux-amd64
          sudo mv oha-linux-amd64 /usr/local/bin/oha
          which oha
          oha --version || echo "oha installed and executable"
          ls -l /usr/local/bin/
          echo $PATH

      - name: Run Tests
        run: |
          # Add commands to run your tests here
          echo "Running tests..." 
          # oha -n 100 -c 10 http://localhost:8080/api/test
      
      - name: Run load test
        run: bash scripts/load_test.sh

      - name: Post results as PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: load_test_results.txt

      - name: Cleanup KinD Cluster
        run: |
          kind delete cluster --name goodnotes-cluster
